model_list:
  - model_name: Qwen2.5-Coder-32B-Instruct
    litellm_params:
      model: huggingface/Qwen/Qwen2.5-Coder-32B-Instruct
      api_key: os.environ/HUGGINGFACE_API_KEY
  - model_name: llama-3.1-8B-instruct
    litellm_params:
      model: huggingface/meta-llama/Meta-Llama-3.1-8B-Instruct
      api_key: os.environ/HUGGINGFACE_API_KEY
  - model_name: DeepSeek-R1-Distill-Qwen-32B
    litellm_params:
      model: huggingface/deepseek-ai/DeepSeek-R1-Distill-Qwen-32B
      api_key: os.environ/HUGGINGFACE_API_KEY
  