provider: autogen_ext.models.openai.OpenAIChatCompletionClient
config:
  model: deepseek-ai/DeepSeek-R1-Distill-Qwen-32B
  base_url: https://api-inference.huggingface.co/v1/
  api_key: ADD_API_KEY
  temperature: 0
  model_info:
    vision: false
    function_calling: true
    json_output: true
    family: r1