provider: autogen_ext.models.openai.OpenAIChatCompletionClient
config:
  model: DeepSeek-R1-Distill-Qwen-32B
  base_url: http://0.0.0.0:4000/v1/
  api_key: os.environ/HUGGINGFACE_API_KEY
  temperature: 0
  model_info:
    vision: false
    function_calling: true
    json_output: false
    family: r1